name: 'Trufflehog Actions Scan'
description: 'Scan repository for secrets with basic trufflehog defaults in place for easy setup.'
author: 'davy Radionoff'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  registry:
    description: 'registry.'
    required: false
  project_id:
    description: 'Project id.'
    required: false
  image_name:
    description: 'image name.'
    required: false
  scanArguments:
    description: 'Argument options for scan.'
    required: false
branding:
  icon: 'shield'
  color: 'yellow'
